# Generated by Django 2.1.1 on 2018-10-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('plot', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('release_date', models.DateField()),
                ('serie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Serie')),
            ],
        ),
    ]
