# Generated by Django 2.1.1 on 2018-11-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20181122_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='nombre',
            new_name='name',
        ),
    ]
