# Generated by Django 2.1.1 on 2018-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('plot', models.TextField()),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
