# Generated by Django 2.1.1 on 2018-11-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(default='hola', max_length=25),
            preserve_default=False,
        ),
    ]
