# Generated by Django 2.1.1 on 2018-11-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='total_rating',
            field=models.FloatField(),
        ),
    ]
